// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/enter": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/subscribe": {
    params: {};
  };
  "/chat": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/enter" | "/login" | "/subscribe" | "/chat";
  };
  "routes/index.tsx": {
    id: "routes/index";
    page: "/";
  };
  "routes/page/start.page.tsx": {
    id: "routes/page/start.page";
    page: "/enter";
  };
  "routes/services/login.service.tsx": {
    id: "routes/services/login.service";
    page: "/login";
  };
  "routes/services/subscribe.service.tsx": {
    id: "routes/services/subscribe.service";
    page: "/subscribe";
  };
  "routes/services/chat.service.tsx": {
    id: "routes/services/chat.service";
    page: "/chat";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/index": typeof import("./app/routes/index.tsx");
  "routes/page/start.page": typeof import("./app/routes/page/startPage.js");
  "routes/services/login.service": typeof import("./app/routes/services/loginService.js");
  "routes/services/subscribe.service": typeof import("./app/routes/services/subscribeService.js");
  "routes/services/chat.service": typeof import("./app/routes/services/chatService.js");
};